### ISSUE TITLE
Synchronous Mode

### ISSUE THREAD

**Issue by f2prateek** [segmentio/analytics-python#101]
I think both https://github.com/segmentio/analytics-python/issues/34 and https://github.com/segmentio/analytics-python/issues/51 are symptoms of the same underlying issue - that our threading does not play nicely with Celery and Google App Engine.

As @calvinfo mentioned in https://github.com/segmentio/analytics-python/issues/51#issuecomment-174096065; the right solution would be to allow users to control/skip the async nature of this library and use it as a dumb HTTP API wrapper when needed.

**Comment by f2prateek** [comment]
Two potential paths we can take here:

1. Make it easier to user the internal models and underly HTTP API wrappers publicly.
2. Add some option to the client so it operates in synchronous mode.

**Comment by russlevy** [comment]
Synchornous mode would be great for me as well.

**Comment by samcheng** [comment]
Russell, I have a modification that has been working for me
(synchronously).  Let put put it up on github (one of these days when I
have time) to share.

**Comment by savraj** [comment]
the solution for google app engine (for me at least) is to use the built in task queue and just use the http api with urlfetch

**Comment by poswald** [comment]
That pull looks good but Is there going to be a way to configure/explicitly specify a `SyncConsumer` even if you're not in AWS Lambda or Google App Engine?

**Comment by samcheng** [comment]
https://github.com/segmentio/analytics-python/pull/105 works for me.  It bypasses the Consumer class entirely.  I've been using it for backfills, which appear to exacerbate the Celery issue.  We're on Heroku instead of GAE, for what it's worth.

**Comment by gojefferson** [comment]
Synchronous mode would be a great feature. I'm having problems using analytics with django-rq, and I think the problem would be solved if I could make synchronous calls when I want to.
