### ISSUE TITLE
About django.

### ISSUE THREAD

**Issue by hobbestigrou** [segmentio/analytics-python#103]
About the documentation of django:

https://segment.com/docs/sources/server/python/#django

It can be interesting to referenced this little django project:

https://github.com/SteelSeries/django-segment

Integrate analytics on django.

**Comment by f2prateek** [comment]
Thanks, I'll take a look at the project. That repo itself is very sparse in documentation though, I've love to see some more documentation around the setup and take aways!

**Comment by hobbestigrou** [comment]
You're right I totally agree with you, that why i made a contribution to the project.

**Comment by nd4p90x** [comment]
Docs have been updated, thank you.
