### ISSUE TITLE
Incorrect order or args to APIError

### ISSUE THREAD

**Issue by jklukas** [segmentio/analytics-python#104]
See https://github.com/segmentio/analytics-python/blob/8c4b39a54075a9ca3dedcf9539099149672a7fdf/analytics/request.py#L35

In that line, the order or arguments to APIError is incorrect, leading to actual error messages looking like:

```
ERROR:segment:error uploading: [Segment] unknown: Bad Request
 (400)
```

What's expected is probably:

```
ERROR:segment:error uploading: [Segment] 400: Bad Request (unknown)
```

**Comment by f2prateek** [comment]
Ah yep, that looks like a typo to me. The constructor is declared as `def __init__(self, status, code, message):`. I've triaged this internally in our JIRA board, https://segment.atlassian.net/browse/LIB-250; we'll post back here when there's an update!

**Comment by jklukas** [comment]
Thanks, @f2prateek !

**Comment by GautamGupta** [comment]
The log format would actually work just fine for the other use case:

https://github.com/segmentio/analytics-python/blob/8c4b39a54075a9ca3dedcf9539099149672a7fdf/analytics/request.py#L33

**Comment by nd4p90x** [comment]
This has been resolved in the latest version of the LIB, thank you.
