### ISSUE TITLE
Max retries exceeded with url: /v1/batch

### ISSUE THREAD

**Issue by EvanFarrell** [segmentio/analytics-python#144]
Getting the following intermittently on my lambda app. It seems about every ~10 requests to `/v1/batch` have the connection refused by `api.segment.io`  

~~~~ 
error uploading: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f293b141080>: Failed to establish a new connection: [Errno 1] Operation not permitted',))
~~~~

requests==2.21.0
analytics-python==1.2.9

**Comment by nd4p90x** [comment]
Max retries is an option in the latest version, thank you.
