### ISSUE TITLE
Excluding one integration.

### ISSUE THREAD

**Issue by dmitry-mukhin** [segmentio/analytics-python#145]
The [docs on destinations](https://segment.com/docs/sources/server/python/#selecting-destinations) do not cover the case when one wants to disable sending events to a specific destination.

I.e. I think it's ambiguous what the following call will result in:

```python
analytics.track('9742', 'Song Played', integrations={
    'Google Analytics': False
})
```

should I add `'all': True` in `integrations` dict or is it implied?

**Comment by heitorsampaio** [comment]
Hey @dmitry-mukhin if you want to use all of your integrations, you don't need to pass the `'all': True` because by default the data is sent to all integrations.
So you just need to pass like that:

```python
analytics.track('9742', 'Song Played')
```

**Comment by nd4p90x** [comment]
@dmitry-mukhin thanks for the question and @heitorsampaio thank you for the response.  If you have any further issues please let us know and we will re-open this ticket.
