### ISSUE TITLE
Override default timeout value

### ISSUE THREAD

**Issue by harshit-sh** [segmentio/analytics-python#149]
Hi, I am using the sdk and using the `analytics.track(...)` and `analytics.identify(...)` calls and I wanted to set the `timeout` parameter to a custom number. I can see that the default value is set to `15` seconds here: https://github.com/segmentio/analytics-python/blob/master/analytics/request.py#L37.

Is there a way to override it? Thanks!

**Comment by nd4p90x** [comment]
This is a configurable option in the newest version.  Thank you.
