### ISSUE TITLE
Is this repository actively maintained? 

### ISSUE THREAD

**Issue by kairichard** [segmentio/analytics-python#152]
There are unanswered issues and pull requests coming in since April. 
The last release was a pre-release also from April which didn't move forward from there. 

As a new segment io customer, I feel like I can't rely on this SDK which makes me question my trust in the company. I would love to see someone taking ownership over this again.

**Comment by p-duke** [comment]
Curious about this as well. The python sdk docs state that you can specify an `upload_size` property on `Client` but that's not available on the stable version 1.2.9. This is something we'd like to use but unsure if 1.3.0b0 or 1.3.0b1 is stable for production use.

Can you please advise to the state of this sdk and whether and the stability or future of the pre-release?

**Comment by colemanja91** [comment]
I would like to echo this. There are several issues I've found with using the distro found on PyPI, and did not realize it until I had installed directly from this repo using a git source instead.

**Comment by jf** [comment]
Nobody from segment commenting?

**Comment by ca-simone-chiorazzo** [comment]
Any news on this? We are a new to Segment we do not know if we have to use the latest beta or the stable release. I would also add that the documentation https://segment.com/docs/connections/sources/catalog/libraries/server/python/ is already pointing to feature that is in beta (I'm referring to the client options)

**Comment by advance512** [comment]
It seems like Segment doesn't care much about Python-based analytics, sadly..

**Comment by dip-thistle** [comment]
Hey everyone, Is this repository still maintained?

**Comment by heitorsampaio** [comment]
Hello guys, sorry about the delay. From now this repo will be back maintained.

**Comment by pooyaj** [comment]
Looks like the `upload_size` is still not configurable.
