### ISSUE TITLE
Rename package to segment-python and use a segment.analytics namespace

### ISSUE THREAD

**Issue by iMerica** [segmentio/analytics-python#154]
Hey guys,

There is a vast ecosystem of "analytics" tools in the Python landscape. Believe it or not, the word "analytics" isn't just about tracking users on the internet.

https://en.wikipedia.org/wiki/Analytics

In acceptance of this reality, it would be very considerate to use a more specific namespace that begins with `segment` e.g `from segment import identify`. This way organizations that use Segment can also have code in their own local `analytics/` directory without a namespace collision (since analytics is a broad area).

**Comment by ca-simone-chiorazzo** [comment]
Any news on this? Due to this naming, we had to refactor an internal package that was clashing with this SDK

**Comment by heitorsampaio** [comment]
Hey guys, thanks for the advice we agree with that, in the next update we will change that.
