### ISSUE TITLE
Request: Test under Python 3.7 and 3.8

### ISSUE THREAD

**Issue by jdevera** [segmentio/analytics-python#155]

**Comment by rohitpaulk** [comment]
This was fixed in https://github.com/segmentio/analytics-python/commit/22090c7aa1477bc0164ff2de92cc7d3d90ac0706#diff-1d37e48f9ceff6d8030570cd36286a61

**Comment by j1fig** [comment]
@rohitpaulk when can we expect a release with the official testing?

**Comment by rohitpaulk** [comment]
@j1fig I don't have an exact date, but soon-ish (within a month or so)
