### ISSUE TITLE
Update to a newer version of the backoff package or relax version restriction

### ISSUE THREAD

**Issue by eirikur-grid** [segmentio/analytics-python#167]
Version 1.6 of [backoff](https://github.com/litl/backoff), which this package depends on, is almost [two years old](https://github.com/litl/backoff/blob/master/CHANGELOG.md#v160---2018-07-14).

I'd like to use a more recent version in my Python 3.8 project but can't due to analytics-python having an exact dependency on version 1.6.0.

**Comment by advance512** [comment]
+1 to this, it is a major issue with the new pip dependency resolver that might break some existing setups.
We are an example, some of our projects use `backoff` of a newer version, which was not a problem until now.

More info:
https://stackoverflow.com/questions/63277123/what-is-use-feature-2020-resolver-error-message-with-jupyter-installation-on

**Comment by XiRoSe** [comment]
I'll add +1 to this issue as well, this breaks existing packages with the new pip-2020-resolver for my repositories as well, it says that the backoff==1.6.0 is a conflict with the newer backoff versions explicitly.

**Comment by advance512** [comment]
Created a PR: #173

**Comment by advance512** [comment]
This has officially become a problem for us in production.
Do you think that Segment will pay more attention to the developers using its services now that it was purchased by Twilio?
@anoonan @lubird @rohitpaulk

**Comment by heitorsampaio** [comment]
Hey guys, sorry about that, in our last PR we added the Dependabot to avoid this kind of things.
