### ISSUE TITLE
Consumer objects stop working after fork()

### ISSUE THREAD

**Issue by greghball** [segmentio/analytics-python#171]
I have discovered that if you fork() your python process, the client in the new process has a consumer with a queue but there's no worker thread to consume anything from the queue, and sending anything just fails silently.

This happened to me when I switched from running our Django project under mod_wsgi to UWSGI. I solved it using the UWSGI "lazy-apps" option, but the analytics module could be improved.

For example, I had so such problem with our Segment client library. If you look at the code for the BackgroundWorker class in the sentry-python project you'll see that each instance maintains a record of the process id at the time its background thread was created; and if that PID changes then a new background thread is created.

https://github.com/getsentry/sentry-python/blob/638a495445b7b7b0292144d29dddd865662498ee/sentry_sdk/worker.py#L20

**Comment by nd4p90x** [comment]
Thank you for your comment, if you feel this is still an issue, please feel free to re-open the ticket.
