### ISSUE TITLE
Unpin `backoff` dependency

### ISSUE THREAD

**Issue by samueldg** [segmentio/analytics-python#188]
The way the `backoff` library is currently specified in the `setup.py` doesn't allow users to upgrade it, as it's pinned to 1.10:

https://github.com/segmentio/analytics-python/blob/bf7168d7cb9bed5b1599928bca4d83fd468f31ce/setup.py#L27

`backoff` recently released 1.11.0 and 1.11.0: https://pypi.org/project/backoff/#history

This seems like the dependency was just not introduced with a permissive semver operator (`>=`, `~=`):
https://github.com/segmentio/analytics-python/commit/3cd1630d3bd576a2ad871341d06cbae0c91b9c1a
but maybe there's a particular reason to keep it that way?

If not I can submit a PR.

**Comment by nd4p90x** [comment]
@samueldg We would just need to ensure that the new version of backoff does not affect current functionality.  If you would like to submit a PR, I would be glad to test and get this moved forward.  Thank you.

**Comment by samueldg** [comment]
@nd4p90x 

Submitted a PR: #189 

The changelog doesn't seem to indicate any breaking change:

https://github.com/litl/backoff/blob/master/CHANGELOG.md#v1110-2021-07-12

but the proof will be in the testing 😄
