### ISSUE TITLE
Latest pull request reverted some changes I made

### ISSUE THREAD

**Issue by samueldg** [segmentio/analytics-python#195]
I recently made some changed in two PRs:
* https://github.com/segmentio/analytics-python/pull/189
* https://github.com/segmentio/analytics-python/pull/191

When I came back to see if the changes had been released, I instead noticed that some of the changes have been reverted, accidentally it seem (?) by PR https://github.com/segmentio/analytics-python/pull/193

For instance, the bug that bought me here in the first place is this dependency pin: https://github.com/segmentio/analytics-python/blob/ea368aef3687747f5c504271a89219084adf34d3/setup.py#L27

The other dependencies are also mostly incorrectly specified, as to possibly take backwards-incompatible changes.

Another line that was possibly lost in translation: https://github.com/samueldg/analytics-python/blob/2085498b4395fefa620d281275617e3843fe1dbc/.circleci/config.yml#L136

Is there any reason not to include Python 3.9 in the end-to-end test?

**Comment by nd4p90x** [comment]
I will look into this, not sure how those changes were reverted just yet.  Thanks
