### ISSUE TITLE
Possibly unnecessary install dependency `appdirs`

### ISSUE THREAD

**Issue by samueldg** [segmentio/analytics-python#196]
The current version of this library on `master` requires installing the `appdirs` library:
https://github.com/segmentio/analytics-python/blob/ea368aef3687747f5c504271a89219084adf34d3/setup.py#L29

If I'm not mistaken, this only seems to be used for CI:
https://github.com/segmentio/analytics-python/blob/ea368aef3687747f5c504271a89219084adf34d3/.circleci/config.yml#L27 which also installs it explicitly. I don't see any other reference to `appdirs` in the actual code.

Perhaps this should be moved to a separate `dev-requirements.txt` or something which is installed during CI and by devs?

**Comment by nd4p90x** [comment]
Looking into this, I do believe you are correct.  Change coming soon
