### ISSUE TITLE
question on not using on_error for next() method

### ISSUE THREAD

**Issue by sushruta** [segmentio/analytics-python#200]
I was grokking the code and saw that `next()` method in analytics/consumer.py file [is not wrapped in a try-catch block](https://github.com/segmentio/analytics-python/blob/master/segment/analytics/consumer.py#L63). Why is it so? What would happen if something were to fail in the method?

specifically look at this line - https://github.com/segmentio/analytics-python/blob/master/segment/analytics/consumer.py#L97

```
item_size = len(json.dumps(item, cls=DatetimeSerializer).encode())
```

It is possible for item to be non-serializable (e.g numpy.float64 type) and throw a `TypeError`. Since this TypeError is not being caught in a try-catch block, it will not be propagated through the `on_error` method. Actually, it doesn't end there. Since, all this is happening in a child daemon thread, that exception could be lost and not logged anywhere.

----------

#### steps to reproduce this issue

```
import numpy as np
import analytics

def log_on_error(error, items):
  print("Print me because an error occurred: ", error)

analytics.write_key = 'some-write-key'
analytics.on_error = log_on_error

vf32 = np.float32(5873.3145)
analytics.track('some-uuid', 'some-str-name', {'some-dict-key': vf32})
```

The expected behavior is to get the error from `log_on_error`. However, the actual behavior is that we have an exception raised -
`TypeError: Object of type float32 is not JSON serializable`.

**Comment by nd4p90x** [comment]
@sushruta I see your issue and will confer with the team regarding adding in the new exception to the list.  Thank you.

**Comment by sushruta** [comment]
thanks a lot @nd4p90x.
