### ISSUE TITLE
Update analytics-python version on pypi

### ISSUE THREAD

**Issue by spencerattick** [segmentio/analytics-python#206]
The latest version of analytics-python is 2.1.0: https://github.com/segmentio/analytics-python/blob/master/HISTORY.md#210--2022-03-04.

The newest available version in pypi is 1.4.0: https://pypi.org/project/analytics-python/. 

Here it is in Segment's code: https://github.com/segmentio/analytics-python/blob/master/segment/analytics/version.py. 

Can we get pypi updated to 2.1.0? 🙏

Thanks!

**Comment by nd4p90x** [comment]
@spencerattick we are currently working on publishing 2.1.0.  It should be available this week.  Thank you.

**Comment by nd4p90x** [comment]
@spencerattick https://pypi.org/project/segment-analytics-python/

Enjoy!

**Comment by pauricthelodger** [comment]
Hey @nd4p90x, would you mind making another release that includes the https://github.com/segmentio/analytics-python/commit/30108501d1e7b438f37eea9953454b0cfb11ddba fix? v2.2.0 won't run for us without it and v2.1.0 isn't available on there
