### ISSUE TITLE
2.1.0 and 2.2.0 are missing from PyPI

### ISSUE THREAD

**Issue by rouge8** [segmentio/analytics-python#211]
2.1.0 and 2.2.0 are tagged in the repo but aren't released on PyPI.

**Comment by nd4p90x** [comment]
The namespace has been updated to better represent the product.  It was also conflicting with other projects that had a similar or same name.
https://pypi.org/project/segment-analytics-python/

**Comment by rouge8** [comment]
Ah, the README still mentions `pip install analytics-python`. I'll open a PR to fix that.

**Comment by nd4p90x** [comment]
@rouge8 That sounds good, I was going to do the same, but please feel free.  Thank you
