### ISSUE TITLE
[Request] Profiles API

### ISSUE THREAD

**Issue by phrfpeixoto** [segmentio/analytics-python#222]
Not sure if this is the place to request features (I couldn't find any on the documentation)...
But It would be great if the python wrappers for Segment could support Profiles API.

**Comment by nd4p90x** [comment]
@phrfpeixoto this is the place!  We will review and discuss this request then decide if it is within our development path.  Keep an eye out for status changes.  Thanks!

**Comment by nd4p90x** [comment]
> @phrfpeixoto this is the place! We will review and discuss this request then decide if it is within our development path. Keep an eye out for status changes. Thanks!

Could you provide a bit more info on the Profiles API you are referring to?  Wasn't sure if you were referring to profilers or something else.  Thanks

**Comment by nd4p90x** [comment]
@phrfpeixoto following up with your request, could we get a little more clarification?  Thank you

**Comment by nd4p90x** [comment]
Thank you for the suggestion, after discussion with the team, we don't currently have any plans to offer an SDK wrapper for Profiles API.
