### ISSUE TITLE
Update backoff dependency?

### ISSUE THREAD

**Issue by joetheone** [segmentio/analytics-python#226]
Hi there!

backoff 1.10.0 was released in late 2019. Any possibility this package could be upgraded to use backoff 2.x.x?

Thanks!

**Comment by janbolmer** [comment]
Any updates here, we are having the same problems - conflict with this dependency

**Comment by nd4p90x** [comment]
@janbolmer @joetheone I will be looking into updating this.  Please give me some time to test and complete the update.  

Thank you,

**Comment by jcalvesoliveira** [comment]
Same problem here. The GitHub repo is already updated, but the new version is not on PyPi yet. Any updates on this?

**Comment by nd4p90x** [comment]
working on this now

**Comment by SimonSchick** [comment]
Was this actually published, still getting version conflicts.

**Comment by SimonSchick** [comment]
Nvm we were still using `analytics-python`, the package name change isn't exactly obvious from the docs :/
