### ISSUE TITLE
Change in date format for originalTimestamp

### ISSUE THREAD

**Issue by shraddha-twilio** [segmentio/analytics-python#235]
Hi Team, 
Based on my discussion with @pooyaj, we discovered that the value for `originalTimestamp` generates the date time string with microseconds instead of milliseconds. This is leading to malformed payloads and Segment is not processing calls with `originalTimestamp` value having sub-millisecond data in them. All other timestamp keys such as `sentAt`, `timestamp` and `receivedAt` have milliseconds in them. 

This behavior was discovered for the Python Server side library 1.4.0 through PyPi. Could you please ensure that we pass milliseconds instead of microseconds for the value of `originalTimestamp` moving forward? 

Example: 
malformed value - `"originalTimestamp": "2022-07-28T21:43:35.291077+00:00"`
corrected value - `"originalTimestamp": "2022-08-02T00:43:35.291+00:00"`

Please let me know if you have any questions. Thanks!

**Comment by MichaelGHSeg** [comment]
Addressed by PR #242
