### ISSUE TITLE
Import analytics clash with standard library module

### ISSUE THREAD

**Issue by terra-alex** [segmentio/analytics-python#237]
Guidelines need to be change from the example mentioning to write

```
import analytics
```

This clashes with python's standard library module also called analytics, and seems to be causing an issue on segment analytics 2.2.1 & Python 3.9.7

Instead, guidelines should be to use
```
import segment.analytics as analytics
```

Just caused an issue on production build for our application

**Comment by nd4p90x** [comment]
@terra-alex Thank you for the request.  We will confirm and update the docs accordingly.

**Comment by MichaelGHSeg** [comment]
The docs have been updated, thank you!

**Comment by terra-alex** [comment]
Hey @nd4p90x ! Just realized that this can be rewritten more easily as 

```
from segment import analytics
```

which makes more sense even 😅 sorry about that!
