### ISSUE TITLE
`import analytics` broken in 2.2.1

### ISSUE THREAD

**Issue by shalabhc** [segmentio/analytics-python#238]
The [documented](https://segment.com/docs/connections/sources/catalog/libraries/server/python/) usage of segment-python-analytics doesn't work anymore with 2.2.1:

With 2.2.0:
```python
% pip install segment-analytics-python==2.2.0
...

% python
Python 3.8.13 (default, Jul  5 2022, 11:00:57) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import analytics
>>> analytics.track
<function track at 0x10974be50>
>>> 
```

With 2.2.1
```python
% pip uninstall segment-analytics-python && pip install segment-analytics-python==2.2.1
...

% python3
Python 3.8.13 (default, Jul  5 2022, 11:00:57) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import analytics
>>> analytics.track
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'analytics' has no attribute 'track'
>>> 
```

Is there a backwards incompatible change that is documented?

**Comment by MichaelGHSeg** [comment]
The recent release included a change related to the new namespace from the 2.0 update.  We didn't realize until this problem cropped up that the namespace change was previously incomplete, and the documentation has just now been updated to reflect the new behavior.

To resolve the issue, please update your import statement to the following:
`import segment.analytics as analytics`
