### ISSUE TITLE
Issue: Messages are getting dropped sometimes and not pushed to segment.

### ISSUE THREAD

**Issue by sugam0099** [segmentio/analytics-python#245]
When sending a batch of 2k messages in async mode with a sleep of 10 sec also, messages are getting dropped.Messages are getting dropped in sync mode when total number of messages are only 2.5k.(We are not getting error message queue is full as messages count is less than default queue size(10k). Everytime there are some discrepancies with the data that been pushed to segment. Everytime different number of records  get dropped running same code.Please assist. Maybe the issue is at the consumer end which is consuming but not able to push.

**Comment by nd4p90x** [comment]
@sugam0099 Is this in the production environment or development?  Thank you

**Comment by MichaelGHSeg** [comment]
Please reopen this issue if you still need assistance.
