### ISSUE TITLE
Deprecate unmaintained PyPI package

### ISSUE THREAD

**Issue by julian-caplena** [segmentio/analytics-python#246]
The old PyPI page with the [previous package name](https://pypi.org/project/analytics-python/1.4.0/) still exists and isn't marked as unmaintained or deprecated.
Ideally this page would show a notice that the package was renamed with a clear migration path.

The README also still mentions "Install analytics-python using pip".

**Comment by nd4p90x** [comment]
@julian-caplena Thank you for that, we will update PyPI and the docs.

**Comment by MichaelGHSeg** [comment]
Thanks for bringing it to our attention.  I finally got the post release pushed with an update to redirect to the newer library.
