### ISSUE TITLE
Python 3.10 and 3.11 support

### ISSUE THREAD

**Issue by aqeelat** [segmentio/analytics-python#251]
Are python 3.10 and 3.11 supported? If so, could you please add the classifiers to setup.py?

**Comment by nd4p90x** [comment]
We will be testing on these version very soon.

**Comment by mvinogradov-wavefin** [comment]
🙏   https://github.com/segmentio/analytics-python/pull/254  🙏

**Comment by nd4p90x** [comment]
I have added those version to the new github actions tests we are converting to, everything is going well and I suspect we can release on those versions soon.  Sorry for the delay.

**Comment by MichaelGHSeg** [comment]
2.2.3 is now released with 3.10 and 3.11.

Cheers!
