### ISSUE TITLE
errors when calling client..

### ISSUE THREAD

**Issue by sirvon** [segmentio/analytics-python#33]
When i call
```python
 client.identity(userid,)

or

analytics.identity(userid,)
```
if get this error....
No handlers could be found for logger "segment"

**Comment by murielsilveira** [comment]
I was getting the same error and I just figured out what was going on by using the development settings in the documentation:

https://segment.com/docs/libraries/python/#development-settings

Then I realized the mistake I was making.
Hope this helps.

```py
def on_error(error, items):
    print("An error occurred:", error)

import analytics
analytics.debug = True
analytics.on_error = on_error
```

**Comment by calvinfo** [comment]
Closing for now, let me know if I should re-open!

**Comment by salvador-dali** [comment]
@calvinfo can you please reopen this one.

```
import analytics
print analytics.__version__

analytics.write_key = "XXX"
def on_error(error, items):
    print("An error occurred:", error)

analytics.debug = True
analytics.on_error = on_error

analytics.track('019mr8mf4r', 'Made a Comment', {
    'that_aided': 'No-One',
    'comment': 'its 4AM!'
})
```

gives me the same error:
```
No handlers could be found for logger "segment"
1.1.0
```

**Comment by calvinfo** [comment]
Hey @salvador-dali you'll need to add a handler for the segment logger to get it to output messages properly. We should add it to our docs as well, but in that case it likely means that your call went through successfully. If you call `analytics.flush()` you should be guaranteed to see it.

To get rid of the handler message, do something like this:

```
import logger

log = logging.getLogger('segment')
log.addHandler(...)
```

Where you add whatever your handler is.

**Comment by salvador-dali** [comment]
@calvinfo thanks for a quick reply. This solved my problem.
