### ISSUE TITLE
track event fails

### ISSUE THREAD

**Issue by stevenmiller888** [segmentio/analytics-python#39]
e.g. analytics.track(1, "Exception", {"fn": lambda x: x })

**Comment by joshkehn** [comment]
To clarify this *silently* fails to send the event. It's way more common to be sending a different non-JSON encodable data structure (like a Django QuerySet, Decimal, or similar) than a inline function but the issue presents either way. 

With an `on_error` function and `debug` flipped on this still silently eats the JSON error.

**Comment by calvinfo** [comment]
Sorry for the long delay here, should be fixed by #54!
