### ISSUE TITLE
Might be an issue with selecting integrations

### ISSUE THREAD

**Issue by stevenmiller888** [segmentio/analytics-python#41]
e.g. { 'all': False, 'Mixpanel': True }

just wanted to get this on here. need to investigate more

**Comment by calvinfo** [comment]
Looks okay to me?

https://www.dropbox.com/s/m3pga5i5ixmd4ym/Screenshot%202015-02-12%2010.43.17.png?dl=0

Are we sure they are using the most recent version of the lib and tracking something like:

```python
analytics.track('user-id', 'event', integrations={'all': False, 'Mixpanel': True })
```

**Comment by stevenmiller888** [comment]
Yup just wanted this up here to make sure I didn't forget to test it. Thanks for doing that! Just tested it and saw the same thing, and verified the event shows up in Mixpanel. Closing!
