### ISSUE TITLE
Allow analytics to operate in passthrough mode

### ISSUE THREAD

**Issue by shakefu** [segmentio/analytics-python#44]
Would you be open to a PR that allows the analytics to operate without a write_key?

This would let developers directly integrate analytics in their apps but not actually write data to the API. Definitely useful for debugging and teams where there are variants of dev, staging, test and demo environments, where it's not appropriate to send data to Segment.

Otherwise a developer has to wrap the analytics API in a bunch of boilerplate to not enable/send data.

There's a couple ways that would make it easy to enable this. One would just to add `analytics.passthrough` and change `analytics._proxy` to not actually create the client instance if that is set, perhaps logging the calls instead.

Another could be to make this the default behavior if `analytics.write_key` is `None` or another known, default value. This has the added advantage of allowing late configuration of the `analytics.write_key` setting, which may be necessary in some large, complex applications (e.g. it would get rid of the need for the Django work-around that you have in the docs.)

**Comment by calvinfo** [comment]
Hey Jacob,

What about something like:

```python
analytics.write_key = 'bogus_test_key'
analytics.send = False
```

Would that fit your use case? It wouldn't send but you'd need to supply a test key that you're using so it wouldn't error out.

**Comment by shakefu** [comment]
Hey, this fell off my inbox. 

We ended up writing a thin wrapper that does passthrough if there's no write_key set. I'll see if I can get a PR together if you're interested.
