### ISSUE TITLE
Segment integration with Gainsight not working from Python

### ISSUE THREAD

**Issue by HKongCC** [segmentio/analytics-python#456]
We currently have Segment + Gainsight integration set up in JS. We are trying to track some events from the python side by sending custom event tracks from Python -> Segment -> Gainsight. We are seeing the event track in the Segment debugger but not in Gainsight. Is destination integration supported with the python client?

**Comment by nd4p90x** [comment]
@HKongCC have you found any resolution to this issue?  I would hazard to guess that if you are seeing events within the Segment debugger, then the integration flow to Gainsight may not be configured properly.  Gainsight integration should work as expected.  I can attempt to replicate your issue if you let me know your current status.

Thanks

**Comment by HKongCC** [comment]
Yes, we got help from the main Segment support team. Learned about how there's a difference between the cloud and client and implemented the Gainsight Cloud PX and it worked on its own.

**Comment by nd4p90x** [comment]
This is excellent news, Thanks you for the update.
