### ISSUE TITLE
daemon thread exception

### ISSUE THREAD

**Issue by mgummelt** [segmentio/analytics-python#46]
This line: https://github.com/segmentio/analytics-python/blob/master/analytics/consumer.py#L15

...during process shutdown causes "Exception in thread Thread-1 (most likely raised during interpreter shutdown)"

this is a known problem with daemon threads: http://stackoverflow.com/questions/20596918/python-exception-in-thread-thread-1-most-likely-raised-during-interpreter-shutd

**Comment by trevoriancox** [comment]
This has been a problem for us too.
