### ISSUE TITLE
Cast non-string objects to string types

### ISSUE THREAD

**Issue by poswald** [segmentio/analytics-python#47]
I previously hit this problem in this library, [fixed it](https://github.com/segmentio/analytics-python/commit/6310705df96fb8ee2faf0538443528f4b08a6850) and my PR was merged. Since then it seems like you rewrote much of it and reintroduced the problem. The problem is basically [with this line](https://github.com/segmentio/analytics-python/blob/fca319715715f54390960f017524e6c8117492d7/analytics/client.py#L204) of code. Here's the scenario:

```
>>> from decimal import Decimal
>>> from six import string_types
>>> isinstance("100.00", string_types)
True
>>> isinstance(unicode(Decimal("100.00")), string_types)
True
>>>
>>> isinstance(Decimal("100.00"), string_types)
False
```

There is no reason to reject decimal types. They serialize to JSON-compatible strings perfectly well. In short: many, many objects developers deal with in python are not strings but can still be serialized out and you probably shouldn't be so aggressive about rejecting them. This happens with Decimals, custom types, lazy localization strings, etc... Your users can all pepper their code with `unicode()` calls to explicitly cast them into the types you need for your JSON transport but the proper way to solve this would be for you to just try casting to whatever types your API expects/support for serialization.

I am not 100% sure but I think this is also the problem outlined in issue #39.

**Comment by calvinfo** [comment]
Sorry for the long delay here, should be fixed by #54!
