### ISSUE TITLE
debug option to client works oddly (and doesn't work in python2.6)

### ISSUE THREAD

**Issue by greghball** [segmentio/analytics-python#48]
When you create an instance of the `Client` class and pass `debug=True`, the `__init__` method will execute

    self.log.setLevel('DEBUG')

and there are 2 problems with this.

1) `self.log` is the logger instance named 'segment' - it's the same instance for every client, so if you create multiple clients you can't use different values for `debug` or things get confused.

2) In python 2.6, you can't say `log.setLevel('DEBUG')`, you have to say `log.setLevel(logging.DEBUG)`, otherwise you're effectively setting the log level to an arbitrary high level and no log messages appear.

Is python 2.6 supported? I can't find any documentation that specifies either way.

**Comment by calvinfo** [comment]
Yes, 2.6 should be supported! I think you've caught a bug on our side, and
we should probably allow some way of configuring the logger passed in.
Happy to accept PRs for that :)

**Comment by calvinfo** [comment]
Fixed in #53
