### ISSUE TITLE
Would it possible to also log response if it is 200 and in debug mode?

### ISSUE THREAD

**Issue by kim5566** [segmentio/analytics-python#481]
We are utilizing the Segment Python client to transmit analytics events to our host.

We have implemented a custom validation message for successful responses.

Additionally, we would like to enable logging of these messages in DEBUG mode. Is it possible to modify this  https://github.com/segmentio/analytics-python/blob/75838879c5b2859f6305bea0970c424198ee278a/segment/analytics/request.py#L61 so that it also logs `res.json()`?

Happy to make code change if accepted

Thank you in advance!

**Comment by nd4p90x** [comment]
@kim5566 

Please feel free to submit a change request for this.

Thank you!

**Comment by kim5566** [comment]
Thanks for your response! @nd4p90x i have raised the PR here: https://github.com/segmentio/analytics-python/pull/491
