### ISSUE TITLE
"No module named analytics" error in Python

### ISSUE THREAD

**Issue by gadybadger** [segmentio/analytics-python#57]
I have followed the [instructions for installing the Python library](https://segment.com/docs/libraries/python/), specifically for Django.

I ran `pip install analytics-python`, but when I try to add `import analytics` anywhere in my project, I get `No module named analytics` in both the PyCharm IDE and when running the app. I have confirmed that I'm using the correct Python Interpreter and `analytics-python` is indeed recognized as being installed. It isn't listed in the docs, but should anything be added to `INSTALLED_APPS`?

Any help to resolve this is much appreciated.

**Comment by hankim813** [comment]
I'll close this based on the date of the issue -- please let me know if this is still an issue and I'll reopen!

**Comment by superprat** [comment]
Ran into the same problem
