### ISSUE TITLE
App Engine Stripped prohibited headers from URLFetch request: ['Content-Length']

### ISSUE THREAD

**Issue by Jonovono** [segmentio/analytics-python#62]
Getting this error running on appengine and the requests get blocked at it. Any idea?

**Comment by thinq4yourself** [comment]
This is a GAE message that you can't turn off, and it seems other people see it regardless of app or endpoint they are reaching via http.

Have you noticed your Segment `analytics.track()` methods are hanging and not returning a response? The vent gets tracked in Segment, but the request is stuck until I clear all requests out of the HTTP server or restart app.
