### ISSUE TITLE
analytics.track() - asynchronous

### ISSUE THREAD

**Issue by patillacode** [segmentio/analytics-python#65]
Hi there,

I have been working with Segment's analytics-python module for a little while now.

Today I discovered that for example the `track` method is *asynchronous*.
I never realized this before, since I usually use it within services that are always up (listeners, queues, etc)

Today I had to do a simple script to read from a file and push some data into my Segment bucket. Surprisingly when I run the super simple script the data didn't get to my Segment debugger, although when I ran the same exact code in a python console it worked like a charm.

I finally saw the problem was that my script finished before the `analytics.track()` function was done.
I added an extra 10 seconds to wait for it to be executed and I made sure that was the problem indeed.

So, is there anyway to make the `track` method wait for itself? Any extra args I could put in? 
Callbacks? Any suggestions?

I took sometime to go through all the options I didn't figure out a way to do it,
any help is greatly appreciated.

Thanks for your time.

**Comment by calvinfo** [comment]
The best thing to do is to add an `analytics.flush()` before your worker exits. It should block execution until all messages are flushed!

**Comment by patillacode** [comment]
Cheers for that @calvinfo 

I didn't see it before, I appreciate.

Thanks again.

**Comment by mgwilliams** [comment]
This is a very old thread, but still shows up on some Google searches. It appears the current solution is to set `sync_mode` to `False`:

https://segment.com/docs/connections/sources/catalog/libraries/server/python/#background-threads-and-synchronous-mode
