### ISSUE TITLE
Give an ability to overwrite messageID

### ISSUE THREAD

**Issue by salvador-dali** [segmentio/analytics-python#66]
Currently I have not found a way to overwrite messageID. Python's library [sets it automatically ](https://github.com/segmentio/analytics-python/blob/master/analytics/client.py#L178)

**Comment by f2prateek** [comment]
This might be tricky to implement without breaking API compatibility.

**Comment by hankim813** [comment]
I'll close this for now as this sounds like more of a feature request-- would be interested in hearing use cases for why you might want to overwrite the messageId

**Comment by nedgar** [comment]
One use case for us is to avoid duplicate events (in Segment and Amplitude) if we re-send events (based on our local store). This avoids having to maintain bookkeeping on which events have been sent already. e.g. I can say: push events in last day, without having to worry about the fact that the last update was ~20 hours earlier, not exactly 24 hours.

**Comment by f2prateek** [comment]
@nedgar yeah I think there are good use cases for this. I'd be open to seeing a PR that adds this without breaking API compatibility.

**Comment by nhi-nguyen** [comment]
Fixed in release [1.3.0b0](https://pypi.org/project/analytics-python/1.3.0b0/).
