### ISSUE TITLE
Remove param={} from all the methods

### ISSUE THREAD

**Issue by m-vdb** [segmentio/analytics-python#67]
Hi there,

The issue with [having mutable default arguments](https://github.com/segmentio/analytics-python/blob/master/analytics/client.py#L44-L45) is [that](http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments). Usually it can be replaced by `param = param or {}` or `param = param or []`.

Max.

**Comment by calvinfo** [comment]
Agreed, happy to accept PRs to fix this behavior!

**Comment by calvinfo** [comment]
Fixed by #68

**Comment by m-vdb** [comment]
ah you were quicker than me. Also, you might want to enable linting in your CI. You would have detected such issues :)

**Comment by m-vdb** [comment]
thanks!
