### ISSUE TITLE
"Python's standard datetime object is broken"

### ISSUE THREAD

**Issue by dwieeb** [segmentio/analytics-python#74]
This is a documentation issue, but I figure it may be best to talk directly to developers. 

https://segment.com/docs/libraries/python/#timezones-in-python

Python datetime objects are not "broken". The Python datetime module, in fact, is one of the best standard library implementations of all the programming languages I've worked with. The Python core devs knew timezones were [difficult to work with](https://www.youtube.com/watch?v=-5wpm-gesOY). Libraries that deal with timezones are gnarly messes of spaghetti code that are constantly updated. Most people use `pytz`, which is able to be versioned independently of your installed Python, instead of being locked into timezones that existed at the date your version of Python was released.

The core team abstracted the timezone madness into the `tzinfo` classes, which you can implement to determine the offsets for a particular date.

`tzinfo` classes are not required to use datetime objects in Python, which is good. It allows you to work with dates in an abstract way. These are called "naive" datetime objects. datetime objects which do have `tzinfo` objects are called "aware" datetime objects. This is documented in the second paragraph of the [datetime module docs](https://docs.python.org/3.5/library/datetime.html).

The following sentence on your docs shows a misunderstanding of how Python datetime objects work.

![image](https://cloud.githubusercontent.com/assets/236501/14128074/03e1c6ca-f5e3-11e5-976d-8131ad766abd.png)

They don't "lose timezone information", whatever that means. You're not giving timezone information to the `now()` function in the first place. Try this: `datetime.datetime.now(tz=pytz.utc)`.

The following image on your docs depict the behavior of naive datetime objects in a way as if you're expecting them to be timezone aware. `now()` doesn't create timezone aware datetime objects unless you pass the `tz` keyword.

![image](https://cloud.githubusercontent.com/assets/236501/14127660/3e12d20c-f5df-11e5-9483-21302fbe6ee4.png)

All you need to do, as a library, is require timezone aware datetime objects. Then you can `isoformat` them and all will be fine.

Please fix the documentation to not hate on Python datetime objects because of a misunderstanding.

**Comment by sigmavirus24** [comment]
> Please fix the documentation to not hate on Python datetime objects because of a misunderstanding.

My recommendation would be to update the documentation to provide an example of how to add timezone information, either with `pytz`, the `datetime` library itself, or (preferably) both. It's not terribly hard and a little Google search should help you find how to do that appropriately.

**Comment by masklinn** [comment]
> They don't "lose timezone information", whatever that means. You're not giving timezone information to the now() function in the first place. Try this: datetime.datetime.now(tz=pytz.utc).

Of note, in Python 3 the maintainers added [a UTC instance to the standard library](https://docs.python.org/3/library/datetime.html#datetime.timezone.utc), and [built-in support for fixed-offset timezones](https://docs.python.org/3/library/datetime.html#timezone-objects). This support has also been added to strptime, so if you parse a datetime string with a fixed-time offset and the `%z` operator you'll get a zoned datetime:
```python
>>> datetime.strptime("2015-03-15T07:54:13-1045", "%Y-%m-%dT%H:%M:%S%z")
datetime.datetime(2015, 3, 15, 7, 54, 13, tzinfo=datetime.timezone(datetime.timedelta(-1, 47700)))
```
You still have to use pytz for "named" timezones.

**Comment by sametmax** [comment]
Or really, just use arrow, which abstract all that stuff, and let you go from and to datetime when you need it.

**Comment by masklinn** [comment]
> Or really, just use arrow, which abstract all that stuff, and let you go from and to datetime when you need it.

Except that's not really what arrow does, it mostly asserts that there's no such thing as a date, a time, or a naive datetime.

**Comment by sperand-io** [comment]
Thanks @dwieeb. Completely agree; point well made and very appreciated. @jgershen to accompany your release this sprint, would you mind updating the docs to reflect the proper approach and remove disparaging/embarrassing language? (And close this once it's done?) Thanks!

**Comment by jgershen** [comment]
Yep, the stuff we had there sure is incorrect & embarrassing; I'll fix the docs. Thanks @dwieeb for bringing it to our attention!

**Comment by jgershen** [comment]
Updated to remove the wrong language and add a brief description of how naive / aware objects work.

**Comment by dwieeb** [comment]
check yo'self

👍 

Thanks, this is great!
