### ISSUE TITLE
No changelog

### ISSUE THREAD

**Issue by adamchainz** [segmentio/analytics-python#75]
I'm upgrading from 1.1.0 to 1.2.3 and I have no idea what has changed

The [docs](https://segment.com/docs/libraries/python/) link to the [github releases atom](https://github.com/segmentio/analytics-python/releases.atom) which is useless as there is no metadata, jsut version numbers

The commit log is not readable when trying to determine the relevance of upgrades.

Please [keep a changelog](http://keepachangelog.com/) and make Segment.io a more useable product.

Thanks!

**Comment by sperand-io** [comment]
Hey @adamchainz,

You're absolutely right. currently, we store these updates in https://github.com/segmentio/analytics-python/blob/master/history.md (and that should give you a sense of what's changed in the meamtime)  but we're working on implementing a completely standardized and more semantically valuable commit message / release message practice across our libs and integrations which, ultimately, will feed a changelog you'll be able to follow from within the product.

Thanks for your feedback; it's duly noted.

Best,

Chris (PM @ Segment)

**Comment by adamchainz** [comment]
Ah thanks. I missed the `history.md` because it was in lower case - normally I scan for HISTORY, NEWS, or CHANGES - 99% of projects have it in uppercase.
