### ISSUE TITLE
_coerce_unicode() is wrong

### ISSUE THREAD

**Issue by m-vdb** [segmentio/analytics-python#84]
Hi there,

I noticed that in your [`clean()`](https://github.com/segmentio/analytics-python/blob/master/analytics/utils.py#L37-L48) function that sanitizes data before sending it to your API, if you encounter an unknown type, you will end up trying to coerce it to unicode, by using the [`_coerce_unicode()`](https://github.com/segmentio/analytics-python/blob/master/analytics/utils.py#L66-L76) function. Unfortunately, this doesn't play well with anything except strings (requires the `decode()` method). And sadly, you only log a warning [here](https://github.com/segmentio/analytics-python/blob/a74f9bd54596ecbce3c378236164ad19da473bb9/analytics/utils.py#L72).

We can do two things:
- really coerce the item to unicode by calling `unicode()` on it if it's not a string (and keep the call to `decode()` if and only if `isinstance(item, basestring)`
- enhance `logging` with more context so that when errors come up, we can actually retry sending the full event (and maybe log at error level)

We circumvented the errors in our codebase by checking that everything is JSON serializable before handing them to the SDK, but I really believe these are must-have enhancements :)

**Comment by m-vdb** [comment]
@jgershen can we improve this here?

**Comment by f2prateek** [comment]
Tracking internally here https://segment.atlassian.net/browse/LIB-116.

I'm not entirely sure what you mean by : `enhance logging with more context so that when errors come up, we can actually retry sending the full event `. Retrying the same message as is will result in the same error being logged.

**Comment by lubird** [comment]
Closing issue. Please re-open if you think this needs to still be addressed.
