### ISSUE TITLE
analytics.flush can hang forever if analytics.send == False

### ISSUE THREAD

**Issue by wojcikstefan** [segmentio/analytics-python#85]
Calling `analytics.flush()` makes the shell hang forever, even keyboard interrupts don't work.

```
In [1]: import analytics

In [2]: analytics.write_key = 'TEST_WRITE_KEY'

In [3]: analytics.send = False

In [4]: analytics.track('fake_user_id', 'Sent Email')

In [5]: analytics.flush()
^C^C^C^C^C^C
```

Two alternative options how to improve the behavior if `analytics.send` is set to `False`:
1. `Client._enqueue` should never put items into the queue (it still makes sense to do everything else that that method does so that its behavior can be covered by unit tests).
2. Let `Client.flush` return immediately or raise an exception saying that flush won't work if `send` is `False` because the consumer is not running.

Personally I prefer the 1st option.

**Comment by f2prateek** [comment]
I'm not totally sure if the `send` parameter is meant to be mutable — it's only meant to be set during initialization.

Neither should flush shouldn't block indefinitely, but I don't think it should raise an exception either (I think the use case is injecting a no-op client), instead it should just do an early return.

If `_enqueue` were to not add to the queue, where would we add the message to the queue?

**Comment by wojcikstefan** [comment]
> I'm not totally sure if the send parameter is meant to be mutable — it's only meant to be set during initialization.

Agreed, but in this case I don't *modify* its value. See https://github.com/segmentio/analytics-python/blob/master/analytics/__init__.py#L48 - the `Client` is initialized upon the first `_proxy` call, which in the sample above happens when I call `analytics.track`.

I think the rest of your comment is covered by #86 .
