### ISSUE TITLE
Not all "tracks" being sent using Celery

### ISSUE THREAD

**Issue by jorgemdnt** [segmentio/analytics-python#96]
Hello there! I have a problem upgrading to versions >1.2.3. 

We had code that was something like this:
```python
for model in model_list:
    # ...
    send_foo_metric.delay(model.company_id, model.id)
```
Inside the task there is the usual `analytics.track`.

Every day this code is ran with about 100 to 150 "models". It worked on every model until we tried to upgrade to 1.2.4 and above. There is no exception thrown, no errors on any tasks, but only about 10% ~ 20% from the tracks are sent. 

I have tried checking the [diff from version 1.2.3 to 1.2.4](https://github.com/segmentio/analytics-python/compare/1.2.3...1.2.4) but there was nothing very obvious to me that could cause the problem. The problem also occurs on the latest version. Can anyone help?

**Comment by f2prateek** [comment]
Closed by #97
